//get reservation constants
export const GET_RESERVATION = "GET_RESERVATION";

export const GET_RESERVATION_SUCC = "GET_RESERVATION_SUCC";
export const GET_RESERVATION_FAIL = "GET_RESERVATION_FAIL";

//create reservation constants

export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const CREATE_RESERVATION_SUCC = "CREATE_RESERVATION_SUCC";
export const CREATE_RESERVATION_FAIL = "CREATE_RESERVATION_FAIL";

// confirm reservation constants

export const CONFIRM_RESERVATION = "CONFIRM_RESERVATION";
export const CONFIRM_RESERVATION_SUCC = "CONFIRM_RESERVATION_SUCC";
export const CONFIRM_RESERVATION_FAIL = "CONFIRM_RESERVATION_FAIL";

//decline reservation constants
export const DECLINE_RESERVATION = "DECLINE_RESERVATION";
export const DECLINE_RESERVATION_SUCC = "DECLINE_RESERVATION_SUCC";
export const DECLINE_RESERVATION_FAIL = "DECLINE_RESERVATION_FAIL";

// delete reservation constants

export const DELETE_RESERVATION = "DELETE_RESERVATION";
export const DELETE_RESERVATION_SUCC = "DELETE_RESERVATION_SUCC";
export const DELETE_RESERVATION_FAIL = "DELETE_RESERVATION_FAIL";
